task_step_one:
  description: 'Execute: doubledValue = context.machineContext.triggerData.inputValue
    * 2'
  expected_output: 'doubledValue: number'
task_step_two:
  description: |
    If context.machineContext.stepResults.stepOne.status == 'success' then incrementedValue = context.machineContext.stepResults.stepOne.payload.doubledValue + 1 else incrementedValue = 0
  expected_output: 'incrementedValue: number'
