task_step_one:
  description: Doubles the input value
  expected_output: doubledValue
task_par_step_one:
  description: Doubles the input value
  expected_output: doubledValue
task_br_step_one:
  description: Doubles the input value
  expected_output: doubledValue
task_cyc_step_one:
  description: Doubles the input value
  expected_output: doubledValue
task_step_two:
  description: Adds 1 to the input value
  expected_output: incrementedValue
task_par_step_six:
  description: Logs the input value
  expected_output: rawText
task_br_step_two:
  description: Adds 1 to the input value
  expected_output: incrementedValue
task_cyc_step_two:
  description: Adds 1 to the input value
  expected_output: incrementedValue
task_step_three:
  description: Squares the input value
  expected_output: squaredValue
task_par_step_two:
  description: Adds 1 to the input value
  expected_output: incrementedValue
task_br_step_four:
  description: Gives the square root of the input value
  expected_output: rootValue
task_cyc_step_three:
  description: Squares the input value
  expected_output: squaredValue
task_step_four:
  description: Gives the square root of the input value
  expected_output: rootValue
task_par_step_three:
  description: Squares the input value
  expected_output: squaredValue
task_br_step_three:
  description: Squares the input value
  expected_output: squaredValue
task_cyc_step_one_loop:
  description: Doubles the input value (loop invocation)
  expected_output: doubledValue
task_step_five:
  description: Triples the input value
  expected_output: tripledValue
task_br_step_five:
  description: Triples the input value
  expected_output: tripledValue
