[project]
name = "mastra_a2_a_client"
version = "0.1.0"
description = "Represents the client-side component that orchestrates A2A interactions with a r"
authors = [{name = "Your Name", email = "you@example.com"}]
readme = "README.md"
requires-python = ">=3.10,<=3.13"

dependencies = [
    "crewai[tools]>=0.152.0",
    "python-dotenv>=1.0.1",
    "pyyaml>=6.0.1",
    # TODO: add PyPI package for custom tool "ToolA2AAPI"
    # TODO: add PyPI package for custom tool "ToolProcessA2AStream"
]

[project.scripts]
mastra_a2_a_client = "main:run"
train      = "main:train"

[tool.uv]
dev-dependencies = []

[build-system]
requires      = ["hatchling"]
build-backend = "hatchling.build"
